server:
  port: 8082

spring:
  application:
    name: cart-service
  profiles:
    active: local
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8858
        port: 8719
      eager: true
      filter:
        enabled: true
      web-context-unify: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  # 修复 Springfox 兼容性问题

feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true  # 开启 Feign 的 Sentinel 支持，这是关键配置

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-group
  service:
    vgroup-mapping:
      ${spring.application.name}-group: default
  registry:
    type: file
  config:
    type: file