hm:
  db:
    host: 101.42.238.233
    port: 3306
    database: hmall
    username: root
    pw: Hm#2024@MySQL
  swagger:
    title: 黑马商城商品管理接口文档
    desc: 黑马商城商品管理接口文档
    package: com.hmall.item.controller